WITH agregat AS (
    SELECT YEAR(DATE_FAC) AS ANNEE
        , CODE_ETABLISSEMENT  
        , CODE_CLIENT
        , CODE_COMMERCIAL
        , CODE_ART
        , SUM(CHIFFRE_AFFAIRE_FAC) as CHIFFRE_AFFAIRE_FAC
        , SUM(QUANTITE_FAC) AS QUANTITE_FAC
    
    FROM (
        SELECT 
            CLI.CODE_CLIENT,
            COM.CODE_COMMERCIAL,
            ART.CODE_ART,
            DAT.DATE_FAC,
            COM.CODE_ETABLISSEMENT,
            SUM(FAC.QUANTITE_FAC) AS QUANTITE_FAC,
            SUM(FAC.CHIFFRE_AFFAIRE_FAC) AS CHIFFRE_AFFAIRE_FAC
        FROM   
            {{ ref('f_facture')}} AS FAC
        INNER JOIN {{ ref('d_client')}} AS CLI ON FAC.CODE_CLIENT = CLI.CODE_CLIENT
        INNER JOIN {{ ref('d_commercial')}} AS COM ON FAC.CODE_COMMERCIAL = COM.CODE_COMMERCIAL AND FAC.CODE_ETABLISSEMENT = COM.CODE_ETABLISSEMENT
        INNER JOIN {{ ref('d_article')}} AS ART ON FAC.CODE_ART = ART.CODE_ART
        INNER JOIN {{ ref('d_date')}} AS DAT ON FAC.DATE_FAC = DAT.DATE_FAC
        GROUP BY 
            CLI.CODE_CLIENT,
            COM.CODE_COMMERCIAL,
            ART.CODE_ART,
            DAT.DATE_FAC,
            COM.CODE_ETABLISSEMENT
    ) AGR
    GROUP BY YEAR(DATE_FAC)
        , CODE_ETABLISSEMENT
        , CODE_CLIENT
        , CODE_COMMERCIAL
        , CODE_ART
)
select * from agregat 
ORDER BY ANNEE DESC